# Write your MySQL query statement below
SELECT
 D.NAME AS DEPARTMENT, 
 E.NAME AS EMPLOYEE,
 E.SALARY AS SALARY
FROM EMPLOYEE AS E
JOIN 
DEPARTMENT AS D
ON E.DEPARTMENTID = D.ID
WHERE E.SALARY = (
    SELECT MAX(SALARY) AS SALARY
    FROM EMPLOYEE AS E2
    WHERE E.DEPARTMENTID = E2.DEPARTMENTID
)