# Write your MySQL query statement below
SELECT
 D.NAME AS DEPARTMENT, 
 E.NAME AS EMPLOYEE,
 E.SALARY AS SALARY
FROM EMPLOYEE AS E
JOIN 
DEPARTMENT AS D
ON E.DEPARTMENTID = D.ID
JOIN
(
    SELECT DEPARTMENTID AS DID, MAX(SALARY) AS SAL
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID
) AS E2
ON E.DEPARTMENTID = E2.DID
WHERE E.SALARY = E2.SAL;
